# Generated by Django 4.2 on 2025-01-20 20:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testplans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('template_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('style', models.CharField(choices=[('encourage', '격려'), ('harsh', '팩폭'), ('polite', '정중'), ('witty', '위트')], max_length=10)),
                ('content', models.TextField(help_text='메시지 템플릿. {username}, {test_name}, {test_date} 변수 사용 가능')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderSetting',
            fields=[
                ('reminder_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_hour', models.IntegerField(help_text='시작 시간 (0-23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('start_minute', models.IntegerField(help_text='시작 분 (0-59)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('end_hour', models.IntegerField(help_text='종료 시간 (0-23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('end_minute', models.IntegerField(help_text='종료 분 (0-59)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('interval_hours', models.IntegerField(choices=[(1, '1시간'), (2, '2시간'), (3, '3시간')], default=1)),
                ('message_style', models.CharField(choices=[('encourage', '격려'), ('harsh', '팩폭'), ('polite', '정중'), ('witty', '위트')], default='encourage', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_setting', to='testplans.testplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
