# Generated by Django 4.2 on 2025-01-21 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_id', models.IntegerField(blank=True, null=True)),
                ('test_name', models.CharField(max_length=50)),
                ('test_date', models.CharField(max_length=50)),
                ('test_place', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
